### ISSUE TITLE
Summarize the current data loading pipeline

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/elasticdl#1222]
An example [command-line](https://github.com/sql-machine-learning/elasticdl/blob/develop/doc/tutorials/elasticdl_local.md#summit-a-training-job) that submits a training job.

```bash
elasticdl train \
  --training_data_dir=/data/mnist/train \
  --evaluation_data_dir=/data/mnist/test \
```

TODO: renmae `--evaluation_data_dir` into `--validation_data_dir`, so to follow the terminology [here](https://en.wikipedia.org/wiki/Training,_validation,_and_test_sets).

Parsing the [training command-line](https://github.com/sql-machine-learning/elasticdl/blob/0b07d1e783f349174f18d89376202040e815b939/elasticdl/python/elasticdl/client.py#L12)

Call function [`elasticdl.train`](https://github.com/sql-machine-learning/elasticdl/blob/0b07d1e783f349174f18d89376202040e815b939/elasticdl/python/elasticdl/api.py#L14).

**Comment by terrytangyuan** [comment]
Keras uses `validation_data` in its `fit()` function as well so I agree the terminology should be reconsidered. 

However, one concern is that based on [this link you gave above](https://en.wikipedia.org/wiki/Training,_validation,_and_test_sets), "validation data" is better for tasks with mixed training + evaluation. If it's evaluation-only job, e.g. via `elasticdl evaluate`, it seems like "test data" is more suitable (a dataset used to provide an unbiased evaluation of a final model fit on the training dataset). Would it be better to keep the current "evaluation_data_dir" so it's suitable for both cases? In my opinion, `evaluation_data_dir` is pretty intuitive since it's the data directory used for **evaluation** tasks (no matter whether this evaluation happens with training or not).

**Comment by brightcoder01** [comment]
The summary has been already added in this PR.
