### ISSUE TITLE
Some workers are spinning while waiting for other workers finish tasks at the end of one epoch.

### ISSUE THREAD

**Issue by brightcoder01** [sql-machine-learning/elasticdl#1233]
In this cluster of N workers, at the end of one epoch, M workers finished their tasks, the other N - M workers are still working. These M workers will get the task of WAIT type to wait until the whole epoch finishes. In this stage, these M workers will spinning in the loop and one cpu will be very busy.

**Comment by chunyang-wen** [comment]
It is safe to keep them online but it will waste computing resources. Maybe the master should have better control of this situation.

+ Deallocate redundant resources
+ If there are still new tasks coming up due to the failure of workers, the master should start enough new workers in order to finish the tasks.

**Comment by chunyang-wen** [comment]
cc @ywskycn

**Comment by brightcoder01** [comment]
The worker will sleep(5) while receiving the WAIT task. Please check the following code snippet.

https://github.com/sql-machine-learning/elasticdl/blob/3b5196ff071474a2e3a2df9aaea2e5e042bb3bbe/elasticdl/python/worker/task_data_service.py#L86-L90
