### ISSUE TITLE
Parameter Server Task Discussion

### ISSUE THREAD

**Issue by skydoorkai** [sql-machine-learning/elasticdl#1261]
# Support multiple PS nodes
- We need to separate PS with the master. As the master uses `model_version` to decide checkpoint and evaluation, PS needs to report `model_version` to the master periodically.
- PS Allocates variables and variable shards into different PS nodes. Workers know the mapping between variables and PS nodes. 

# PS stores two types of items
- For non-embedding variables, key = variable_name, value = tf.Variable
- For embedding table, partition the table into PS nodes. key = layer_name + id, value = vector

# Fault-tolerant
- Each worker has a copy of non-embedding variables.
- Embedding vectors in a PS node can have some replicas in other PS nodes. Users can specify the number of replicas `r`. When a PS node `PS_i` updates some embedding vectors, it informs corresponding PS replica nodes `PS_i+1+j for j in range(r)` the updates. Replica nodes decide when to update the replicas by pulling the updated vectors from `PS_i`.
- When a PS node fails, the ElasitcDL master will re-create the PS node pod. The PS node will recover non-embedding variables from workers, and embedding vectors from replicas in other PS nodes. PS pods have higher priority than worker pods, so the resources for the re-created PS node pod is guaranteed.

# PS  = kv-store + variable update + embedding service
Beside kv-store, PS should also support variable updates from the gradients and embedding table sparse lookup with a combiner. GRPC calls to support:
- `GetVariable`: get variables from the PS node (a rename of  the current `GetModel` GRPC call)
- `ReportVariable`: since each PS node has a portion of the model, the PS node should not initialize the whole model. Workers can do the variable initialization and send variables to the corresponding PS nodes.
- `ReportGradient`: use an optimizer to update the variables.
-  `lookup_embedding(keys)`: return embedding vectors
- `sparse_lookup_embedding(keys, combiner)`: combiner is a reduction op. Return the embedding reduction result. May be combined with `lookup_embedding` into one GRPC call.
- `update_embedding(keys, vectors)`: update embedding vector values

# PS implementation programming language
- Because we have to use Python for the TensorFlow optimizer's `apply_gradient`, we must use **Python** for GRPC call implementation.
- Embedding GRPC calls may be accelerated by multi-threaded **C++** functions wrapped by SWIG.

**Comment by QiJune** [comment]
Does the model version mean how many times a parameter is updated?  It seems that the model version in each PS is the same.

**Comment by brightcoder01** [comment]
- Does parameter server store all the non-embedding variables? If yes, how about recover the non-embedding variables from the neighborhood PS instead of worker?

- Worker stores the mapping of <variable, PS>, PS contains the PS index and ip:port, if one parameter server is preempted and relaunched, how to refresh the PS route mapping in worker?

- For Async SGD, how to decide the model_version? Is it updated each time when we apply one gradient? 

- "PS needs to report model_version to the master periodically" => Does all the PS replica report to the master at the same time?

**Comment by QiJune** [comment]
It seems that in ASGD, the model version would lost its meaning. Since the model could be updating partially in pserver, and the partially model is used by a worker. So, it's hard to say the what's the model version of a partially updated model.

And this case also exists in BSP mode. Some pserver is quicker than other pserver, so when worker get parameters from several pservers, some is updated already, some is still under updating.

**Comment by terrytangyuan** [comment]
> Replica nodes decide when to update the replicas by pulling the updated vectors from PS_i.

How exactly do replicas decide when to update? Checking whether the embedding vectors are updated in PS_i frequently may introduce some non-trivial overheads. We may also want to expose the parameters for this in addition to the number of replicas.
